name: Generic

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build to GitHub Packages
        run: ./gradlew build
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  call-workflow-passing-data:
    permissions:
      contents: read
    #  pull-requests: write
    uses: ./.github/workflows/variables.yml
    with:
      config-path: .github/generic.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}